capp/__init__.py
from flask import Flask

application = Flask(__name__)

from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app


application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)

capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint

carbon_app = Blueprint('carbon_app', __name__)

@carbon_app.route('/carbon_app')
def carbon_app_page():
    return render_template('carbon_app.html', title = 'carbon_app')

capp/home/routes.py
from flask import render_template, Blueprint

home = Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_page():
    return render_template('home.html', title = 'home')   

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology = Blueprint('methodology', __name__)

@methodology.route('/methodology')
def methodology_page():
    return render_template('methodology.html', title = 'methodology' )

capp/templates/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_page')}}" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(2, 98, 2);">Methodology</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(2, 98, 2);", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(2, 98, 2);">Your emissions</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:black; text-align: center;">Carbon App, instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:black">
                    <p style="text-align: left;">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae ratione tempore id esse nobis molestias quasi explicabo possimus ea reprehenderit.
                    </p>
                    <ol style="text-align:left;">
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                    </ol>
                    </div>
          
                    <div class="modal-footer">
                    <button class="btn btn-secondary btn-lg mr-2", style="background-color:#6c757d;" data-dismiss="modal">Close</button>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/calculator.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 
       

{% endblock content %}

capp/templates/home.html
{% extends "layout.html"%}
{% block content %}

<section class="section_header_home">
    <div class="container">
  
      <div class="header_home">
        <div class="box"> 
          <h1 style="font-size:55px;"> Home</h1>
          <p style="text-align:left;">
            Welcome to Carbon Tracker, your go-to app for identifying and mitigating carbon emissions for both individuals and organizations. Our app is crafted to assist you in pinpointing the primary contributors to your carbon footprint and guiding you towards meaningful actions to minimize your environmental impact.
          </p>
          <div class="container_buttons_header_home">
            <div class="btn">
                <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#0b7f16;">Register</a>
            </div>
            <div class="btn">
                <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#0b7f16;">Login</a>
            </div>
          </div>  
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/carbon_app.svg')}}"
            width="325" 
            height="325"
            alt=""/>
        </div>
      </div>
  
    </div>
</section> 
<!-- Developers -->
<section class="section_developers">
    <div class="container">
  
      <div class="developers" style="display:block;">
        <h1 style="text-align:center;"> Our Team</h1>
        <p>
        </p>      
      </div>
  
      <div class="developers">
          <div class="box" >
            <img src="static/icons/IMG_0037.jpg" alt="" style="border-radius: 50%; width: 200px; height: 200px;" >
            <h3>Emelie Nyström</h3>
            <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
            </p>
            <div class="container_buttons_developers">
              <a class="btn_developers" href="#"  target="_blank">LinkedIn</a>
            </div> 
          </div>
          <div class="box">
            <img src="static/icons/Fredrik.png" alt="" style="border-radius: 50%; width:200px; height: 200px;">
            <h3>Fredrik Sælemyr</h3>
            <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
            </p>
            <div class="container_buttons_developers">
              <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
            </div> 
          </div> 
          <div class="box">
            <img src="static/icons/Elsa1.png" alt="" style="border-radius: 50%; width:200px; height: 200px;">
            <h3>Elsa Brunet</h3>
            <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
            </p>
            <div class="container_buttons_developers">
              <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
            </div> 
          </div>    
          <div class="box">
            <img src="static/icons/IMG_Green.png" alt="" style="border-radius: 50%; width:200px; height: 200px;">
            <h3>Julen Gago</h3>
            <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
            </p>
            <div class="container_buttons_developers">
              <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
            </div> 
          </div>   
      </div>
  
      <div class="developers">
        <div class="box2">
          <img src="https://randomuser.me/api/portraits/women/13.jpg" alt="" style="border-radius: 50%; width:200px; height: 200px;">
          <h3>Sondre Bøygard</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>
        <div class="box2">
          <img src="static/icons/Thomas.png" alt="" style="border-radius: 50%; width:200px; height: 200px;">
          <h3>Developer 6</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>           
        <div class="box2">
          <img src="static/icons/Alexander.png" alt="" style="border-radius: 50%; width:200px; height: 200px;">
          <h3>Developer 7</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>  
        <div class="box2">
          <img src="https://randomuser.me/api/portraits/women/13.jpg" alt="" style="border-radius: 50%; width:200px; height: 200px;">
          <h3>Developer 8</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>  
    </div>

           
    </div>
    </div>          
</section>
         

 
{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Font Awesome code -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <!--Import the Bootstrap CSS file -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
          
    <!-- CSS code -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='weekly challenge.css') }}">

    <!---To activate media queries(access trough mobile phone)-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <!-- Matjax -->
     <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
     <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

    {% if title %}
        <title>{{title}}</title>
    {% else %}
        <title>home</title>
    {% endif %}


</head>
<body>
    <!--CSS file code-->
    <header class="section_navbar">
        <nav class="navbar">
            <ul>
                <li class="logo">
                    <h3>
                        <a href="{{url_for('home.home_page')}}" class="logo-link"  >
                        <span class="text-logo" style="color: rgb(5, 69, 5);"><i class="fa-solid fa-leaf" style="color: rgb(5, 69, 5);"></i>Carbon App</span>
                        </a>
                    </h3>
                </li>
                <li>
                    <a href="{{url_for('home.home_page')}}">Home</a>
                </li>
                <li>
                    <a href="{{url_for('methodology.methodology_page')}}">Methodology</a>
                </li>
                <li>
                    <a href="{{url_for('carbon_app.carbon_app_page')}}">Calculator</a>
                </li>
   
                 
            </ul>
        </nav>
    </header>



    <main>
    {% block content %} {% endblock %}
    </main>
    <section class="section_footer">
        <div class="container">
          <div class="footer">
            <h1>
              Carbon App 
              <a href="#">
                <i class="fa-solid fa-circle-up" style="color:white"></i>
              </a>
            </h1>
          </div>
        </div>
      </section>
   <!-- <footer>
        <div class="flex_container_footer">
            <div class="Item">Carbon App</div>
        </div>
    </footer> -->
    <!-- Bootstrap JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
      
</body>
</html>

capp/templates/methodology.html
{% extends "layout.html"%}
{% block content %}
<!-- Header -->
<section class="section_header_methodology">
    <div class="container">
  
      <div class="header">
        <div class="box"> 
          <h1 style="font-size:55px;"><span class="text-logo"> Methodology</span></h1>
          <p style="text-align:left;">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
          </p>
          <div class="container_buttons_links_header">
            <div class="btn">
                <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(2, 98, 2);">Paper</a>
            </div>
            <div class="btn">
                <a href="{{url_for('carbon_app.carbon_app_page')}}" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(2, 98, 2);">Calculator</a>
            </div>
          </div>  
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/methodology2.svg')}}"
            width="325" 
            height="325"
            alt=""/>
        </div>
      </div>
      
    </div>
</section> 
<!-- Methodology -->
<section class="section_body_methodology">
    <div class="container">
  
        <div class="methodology" style="display:block;">
            <h1 style="text-align:center;"> Methodology</h1>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut? Praesentium quidem sunt perspiciatis doloremque fugiat nesciunt quaerat ullam, pariatur iure unde ratione ipsum adipisci repellendus, repudiandae hic sit, temporibus molestias corrupti aut soluta sequi! Architecto deleniti expedita nisi repudiandae enim eum quas odit facilis placeat neque porro, animi incidunt consectetur. Maiores ab saepe tempora, iure asperiores beatae suscipit cum ipsum, rerum doloremque reprehenderit dolorum debitis, aliquam quasi. Maiores corporis fuga quasi nesciunt dolor iste, inventore necessitatibus unde!
            </p>      
        </div>

        <div class="methodology" style="display:block;">
            <h1 style="text-align:center;"> Our numbers and formulas</h1>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut? 
            </p> 
        </div>

        <!--Enumerated list (table)-->
        <div class="methodology">              
            <div class="box_table">
                      
            </div>
            <div class="box_table">
                <ol>
                    <li>
                        <h4>Buses</h4>
                        <p class="text-left">
                            The <strong>carbon dioxide emissions</strong> produced by buses are organized in <strong>four categories</strong>. The carbon dioxide emission produced by diesel buses is 0.10231 grammes per kilometer. The carbon dioxide emission produced by CNG buses is 0.08 grammes per kilometer. The carbon dioxide emission produced by petrol buses is 0.10231 grammes per kilometer. If the buses do not use fossil fuel, their dioxide carbon emissions are 0 grammes per kilometer.
                            <br>
                            To work out buses dioxide emissions, we use the next formula:
                            \[CO^2 = {Cte + \sqrt{f(km)} \over t}.\]
                            <br>
                            Where:
                            <ul style="text-align:left;">
                                <li>
                                    \(Cte\) is a constant, since the engine requires some fuel to initialize.
                                </li>
                                <li>
                                    \(km\) are the kilometers.
                                </li>
                                <li>
                                    \(f\) is a coefficient depending on the type of fuel (see paragraph above).
                                </li>
                                <li>
                                    \(t\) is the temperature, since in winter the engines require less fuel.
                                </li>
                            </ul>
                            
                        </p>
                    </li>
                    <li>
                        <h4>Cars</h4>
                        <p class="text-left">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum molestias minus nam, magnam error magni inventore rem debitis est, odio explicabo ducimus! Accusantium libero amet, cum tenetur earum dolores perferendis!
                        </p>
                    </li>
                    <li>
                        <h4>Planes</h4>
                        <p class="text-left">
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus, aspernatur eos, ab necessitatibus iusto quos vel odit praesentium asperiores repudiandae reprehenderit aut similique veniam eius provident. Quibusdam harum doloribus facere tenetur qui cupiditate, deleniti, rerum enim voluptas eligendi, vel quod.
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table">
                      
            </div>  
        </div>
      
    </div>
</section>


{% endblock content %}